version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tennis-app
    ports:
      - 8010:80
    volumes:
      - .:/var/www/html
    environment:
      - APP_ENV=local
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=tennis
      - DB_USERNAME=root
      - DB_PASSWORD=password123
    depends_on:
      - db
  db:
    image: mysql:5.7
    ports:
      - 3316:3306
    environment:
      - MYSQL_DATABASE=tennis
      - MYSQL_ROOT_PASSWORD=password123
